### ISSUE TITLE
App fails when using Magnifier 

### ISSUE THREAD

**Issue by 40-02** [Phaiax/PxKeystrokesForScreencasts#2]
App fails when using built-in windows Magnifier program (shortcut "win" + "0")

System MS Server 2012 x64 via Remote Desktop

**Comment by alganet** [comment]
Can confirm something similar. Every Win+Something shortcut I use leads to a crash. Windows 10.

**Comment by Phaiax** [comment]
I may take a look as soon as Win 10 is ready to install for me.
-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by alganet** [comment]
@Phaiax I'm willing to help and try to fix it! Will report here what I found.

Is there anything specific I should know about building it? 

Thank you!

**Comment by Phaiax** [comment]
Please try. It was a very stupid mistake. I can't believe I have not tested using Win+xxx shortcuts.

**Comment by alganet** [comment]
It seems to be fixed. Thank you!
