### ISSUE TITLE
Ctrl+Alt+Shift Shortcut Replacement (with e.g. a button in Settings)

### ISSUE THREAD

**Issue by mbbmbbmm** [Phaiax/PxKeystrokesForScreencasts#20]
Apart from the modifier key suggestion metadirective brought up this is the main reason that keeps me from recommending this program to Blender users any chance I get - it really seems like it is the best of the free ones.

But in Blender Shift+Alt+Crtl+C is used to set the origin. And I am sure there are other programs using that combination as well. If a toggle button was used instead, that would not be as convenient but more compatible. Or maybe add the OS-Key as the fourth key to the chord. Still pressable but less likely to be in use.

Thank you!

**Comment by mbbmbbmm** [comment]
Ok I forked the repo and added the left Win key to the resize chord. Works good so far. Let me know what you think, if you would consider something like this.

**Comment by Phaiax** [comment]
thx, Ill take a look (soon :D)

**Comment by mbbmbbmm** [comment]
Cool! Maybe I can also try to implement the other suggestion - the option to have the modifier keys always displayed for more shortcut-oriented workflows. I'll see if I find some time and if I understand the code. :D

**Comment by TobiasMalikowski** [comment]
Hey Phaiax,

first thank you for creating this nice app. I'm using Parallels (Virtual Machine) to use Windows 10 on my mac. Only issue I'm facing is the shortcut to move the area which displays the shortcut is not working. Could you please add an option into the Settings to change the shortcut or just enable dragging of the display area, while the settings are opened?

Cheers, Tobias

**Comment by Phaiax** [comment]
Both added. Will be available in next release.
