### ISSUE TITLE
obscured by taskbar if clicked

### ISSUE THREAD

**Issue by timabell** [Phaiax/PxKeystrokesForScreencasts#24]
If you drag the overlay over the task bar, and then click the task bar then the task bar sits on top of the overlay. Which is a shame because with my vertical task bar it would have been a good space to put it.

![obscured px keys](https://cloud.githubusercontent.com/assets/19378/23662687/452269f0-0348-11e7-9b09-75e00ce595c7.PNG)

Thanks for a great tool

**Comment by Phaiax** [comment]
In the next version, there will be a setting "Put on top periodically".
When activated, the window will be lifted upon the taskbar every second.
This makes it flicker if you click the taskbar but at least it comes back after a while.

Fix will be included in next major release. Closed.
