### ISSUE TITLE
Have text disappear after a certain timeout

### ISSUE THREAD

**Issue by PolyglotOpenstreetmap** [Phaiax/PxKeystrokesForScreencasts#3]
Hi Phalax,

Would it be possible to let the text disappear, after maybe 20 or 30 seconds? Now everything I type stays there until I type (lots) more. Which is a bit strange when starting a new screencast session. Alternatively maybe a hotkey to clear the buffer, but I can understand if you want to have as few hotkeys as possible, to avoind clashes with the app that is being demoed.

Jo

**Comment by Phaiax** [comment]
That would be easier to implement. See #4 .

**Comment by Phaiax** [comment]
same as #4 
Commit reference: 6cee338 c0fcff4
