### ISSUE TITLE
Coursor overlay is not correct when you have 2 screens

### ISSUE THREAD

**Issue by Czester16** [Phaiax/PxKeystrokesForScreencasts#39]
I have 2 screens, both 4k - I don't know if it is problem, but mouse position is calculated from left top corner and there every thing looks ok. But when I am close center mouse overlay had twice bigger distance than mouse coursor. When I came at second screen overlay dissapear on right site.
There is something with position calculation.

**Comment by ephestione** [comment]
Something similar happens to me, but it's because screen scaling. I have it at 125%, and the farther I get from the top-leftmost corner, the farther away is the overlay from the real mouse position.

**Comment by Phaiax** [comment]
Will be fixed soon, I am working on a new version that supports multi dpi setups. Closing this issue since there are a lot of duplicates for this issue😸
