### ISSUE TITLE
Keys [+] not always displayed

### ISSUE THREAD

**Issue by accnetdev** [Phaiax/PxKeystrokesForScreencasts#40]
Hi,
I use the modified version (white halo free, but the other version has a similar issue) and I noticed that the [+] key is not always displayed.
To reproduce the bug, launch the app, type [+], the first is diplayed, then [+] are no longer displayed as long as you don't type [Enter]. It seems that the [+] are produced but not visible.

**Comment by Phaiax** [comment]
I can reproduce this, so will be fixed with v2.0 soon

**Comment by Phaiax** [comment]
Fixed. Will be available in next release.
