### ISSUE TITLE
Deactivate/active keystroke logging

### ISSUE THREAD

**Issue by mcse2k1983** [Phaiax/PxKeystrokesForScreencasts#41]
I am a big fan of this software and would have a feature request. Would it be possible to add a checkbox to disable keystroke logging. Often I only need the mouse position. Would be a great additional feature for me. Thanks in advance!

**Comment by Phaiax** [comment]
Good idea
Added to roadmap for v2.0

**Comment by Phaiax** [comment]
Implemented in branch devel. Will be available with next release.

**Comment by mcse2k1983** [comment]
Many thanks for the update! Makes my life so much easier, I will recommend the software to anyone who needs this feature!

When will this version be available as downloadable exe?
