### ISSUE TITLE
Support for scaled resolution

### ISSUE THREAD

**Issue by mau-lopez** [Phaiax/PxKeystrokesForScreencasts#42]
Wonderful piece of software. The problem I'm having is that with a scaled resolution monitor, the mouse pointer appears on one point on the screen and the red circle appears far from the cursor to the left and bottom, the only point in which both coincide is the upper right corner of the display. As I move the cursor away from the upper left corner, the displacement of the red circle relative to the mouse pointer gets bigger and bigger. If I turn off scale resolution in Win settings, the problem disappears, but then everything in my screen looks to big. Hope you can add scaled resolution to this great app. Regards

MacBook Pro Early 2015 13" Retina display (2560 x 1600 px), Win 10 oct 2019 update

**Comment by daneisinger** [comment]
Same issue, same platform.

**Comment by Phaiax** [comment]
Will be fixed soon, I am working on a new version that supports multi dpi setups. Closing this issue since there are a lot of duplicates 😸
